# Use official PostgreSQL image
FROM postgres:latest

# Set environment variables used in prisma service
ENV POSTGRES_DB = coinsync
ENV POSTGRES_USER = admin
ENV POSTGRES_PASSWORD = admin

# Expose the PostgreSQL port
EXPOSE 5432